pocket:
  datasource:
    node:
      - url: jdbc:mysql://127.0.0.1:3306/home?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        nodeName: mysql-01
        driverName: com.mysql.cj.jdbc.Driver
        showSql: true
        collectLog: true
        user: root
        password: root
        poolMiniSize: 10
        poolMaxSize: 60
        timeout: 1000
        retry: 5
        cacheSize: 1000
        session: homo,user
      - url: jdbc:mysql://127.0.0.1:3306/home?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        nodeName: mysql-01-02
        driverName: com.mysql.cj.jdbc.Driver
        showSql: true
        collectLog: true
        user: root
        password: root
        poolMiniSize: 10
        poolMaxSize: 60
        timeout: 1000
        retry: 5
        cacheSize: 1000
        session: order,commodity

server:
  port: 8081
  servlet:
    context-path: /
spring:
  data:
    redis:
      repositories:
        enabled: false
